### ISSUE TITLE
Can't install via Bower

### ISSUE THREAD

**Issue by feniixx** [zingchart/ZingChart-AngularJS#9]
I get the following error:

```
bower zingchart-angularjs#*     cached git://github.com/zingchart/ZingChart-AngularJS.git#1.0.6
bower zingchart-angularjs#*   validate 1.0.6 against git://github.com/zingchart/ZingChart-AngularJS.git#*
bower zingchart#*           not-cached git://github.com/zingchart/ZingChart.git#*
bower zingchart#*              resolve git://github.com/zingchart/ZingChart.git#*
bower zingchart#*             download https://github.com/zingchart/ZingChart/archive/2.2.1.tar.gz
bower zingchart#*              extract archive.tar.gz
bower zingchart#*                EPERM EPERM: operation not permitted, open 'C:\Users\fenix\AppData\Local\Temp\DESKTOP-J
KT2N66-fenix\bower\zingchart-12224-Vs6heu\client\modules\zingchart-maps-usa_ks.min.js'

Stack trace:
Error: EPERM: operation not permitted, open 'C:\Users\fenix\AppData\Local\Temp\DESKTOP-JKT2N66-fenix\bower\zingchart-122
24-Vs6heu\client\modules\zingchart-maps-usa_ks.min.js'
    at Error (native)

Console trace:
Error
    at StandardRenderer.error (C:\Users\fenix\AppData\Roaming\npm\node_modules\bower\lib\renderers\StandardRenderer.js:8
2:37)
    at Logger.<anonymous> (C:\Users\fenix\AppData\Roaming\npm\node_modules\bower\bin\bower:110:22)
    at emitOne (events.js:77:13)
    at Logger.emit (events.js:169:7)
    at Logger.emit (C:\Users\fenix\AppData\Roaming\npm\node_modules\bower\node_modules\bower-logger\lib\Logger.js:29:39)

    at C:\Users\fenix\AppData\Roaming\npm\node_modules\bower\lib\commands\index.js:48:20
    at _rejected (C:\Users\fenix\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:844:24)
    at C:\Users\fenix\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:870:30
    at Promise.when (C:\Users\fenix\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:1122:31)
    at Promise.promise.promiseDispatch (C:\Users\fenix\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:788:41
)
System info:
Bower version: 1.6.6
Node version: 4.2.2
OS: Windows_NT 10.0.10240 x64
```

I also tried running cmd as administrator but same error, I don't understand it...

**UPDATE:**
I find out that my antivirus (Bitdefender) is detecting an infected file, here's what it says:

![problem](https://cloud.githubusercontent.com/assets/15699775/11459054/7450f9e4-9693-11e5-94d4-752048723249.PNG)

**Comment by mike-schultz** [comment]
Strange that its singling out the kansas state map as a virus, but I can assure you that it does not include any viruses and the file contents is very similar to the rest of the maps, just different coordinates for drawing. The file itself is actually included as a dependency from the main library's bower repo here : https://github.com/zingchart/ZingChart. 

I would recommend downloading the zingchart-angularjs directive and the main library directly if you are having issues with your antivirus

**Comment by feniixx** [comment]
I just excluded the app folder from the scan and it worked...
